### ISSUE TITLE
Question on context ?

### ISSUE THREAD

**Issue by windmaomao** [wooorm/state-toggle#4]
thanks for this utility, very nice piece. Couple of question, 

The syntax is `context` is designed as the last parameter, if following the convention of `call` (or `apply`), this parameter is normally the first parameter. 

Also by looking at this piece, it kinda of makes me wonder if react `hook` (ex. `useState`) is using the similar way to provide the global variable as local variable to the current scope.

Thanks.

**Comment by wooorm** [comment]
The reason for ctx second is that it’s optional, so third made more sense for that. E.g., if it’s added on a prototype: `Thing.prototype.enterHouse = stateToggle('isInHouse', false)`, will mutate `isInHouse` on instances!

About React: I don’t know! I don’t use React myself, I just looked a bit through their code but it wasn’t immediately clear to me what they’re doing!

**Comment by wooorm** [comment]
Alright, closing this. If there are more things you’d like to know, feel free to comment here!
